version: "3"
services:
  vmkweb:
    # replace username/repo:tag with your name and image details
    image: vmk1983cloud/myrepo:mytag
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
